In [74]:
import os
import cv2
import numpy as np
from PIL import Image
import pickle

In [71]:
image_dir=os.path.join("./","images")

In [72]:
current_id=0
label_ids={}
y_labels=[]
x_train=[]
face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_alt2.xml")

In [73]:
for root,dirs,files in os.walk(image_dir):
    for file in files:
        if file.endswith("png") or file.endswith("jpg") or file.endswith("jpeg"):
            path=os.path.join(root,file)
            label=os.path.basename(root)
            print(label,path)
            if not label in label_ids:
                label_ids[label]=current_id
                current_id +=1
            id_=label_ids[label]
            print(label_ids)
            #y_labels.append(label) #some number
            #x_train.append(path) #verify this image,turn into a NUMPY array,Gray
            pil_image=Image.open(path).convert("L")
            image_array=np.array(pil_image,"uint8")
            print(image_array)
            faces=face_cascade.detectMultiScale(image_array,scaleFactor=1.5,minNeighbors=5)
            
            for x,y,w,h in faces:
                roi=image_array[y:y+h,x:x+w]
                x_train.append(roi)
                y_labels.append(id_)

emaila ./images\emaila\1.jpg
{'emaila': 0}
[[171 179 187 ... 199 199 199]
 [171 179 187 ... 199 199 199]
 [171 179 187 ... 199 199 199]
 ...
 [209 189 139 ... 171 173 174]
 [194 211 222 ... 171 171 171]
 [155 209 206 ... 171 171 170]]
emaila ./images\emaila\2.jpg
{'emaila': 0}
[[107 107 106 ... 108 107 106]
 [107 107 106 ... 108 106 105]
 [106 106 106 ... 108 107 106]
 ...
 [ 34  35  36 ...  13  13  13]
 [ 34  35  36 ...  13  13  13]
 [ 34  35  36 ...  13  13  13]]
emaila ./images\emaila\3.jpg
{'emaila': 0}
[[ 0  0  1 ...  3  4  4]
 [ 0  0  1 ...  3  4  4]
 [ 0  0  2 ...  3  4  4]
 ...
 [78 80 83 ... 15 15 15]
 [73 79 87 ... 15 15 15]
 [72 83 86 ... 21 16 16]]
emaila ./images\emaila\4.jpg
{'emaila': 0}
[[ 38  42  45 ...  28  28  29]
 [ 41  44  46 ...  28  28  28]
 [ 44  46  47 ...  29  28  27]
 ...
 [104 104 104 ...  23  24  25]
 [108 108 107 ...  23  24  25]
 [113 112 111 ...  23  24  25]]
emaila ./images\emaila\5.jpg
{'emaila': 0}
[[ 31  32  35 ...   0   0   0]
 [ 31  32  34 ...   0 