In [122]:
import cv2
import urllib.request as ul
import numpy as np

In [123]:
face_cascade=cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

In [124]:
face_cascade

<CascadeClassifier 0A8EDC90>

In [125]:
img=cv2.imread("imd.jpg")
 

In [126]:
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)


In [127]:
faces=face_cascade.detectMultiScale(gray_img,
      scaleFactor=1.1,
      minNeighbors=5)
#start from the originale size and decrese the image for 5% and search for bigger faces
for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)

In [128]:
print(faces)
#157 is row length from left
#84 is colomn length from top
#379 is width 
#379 is heigth

[[ 53 203 214 214]
 [388  22 215 215]
 [372 375  60  60]
 [217  39 145 145]]


In [129]:
cv2.imshow("galaxy",img)
cv2.waitKey(0)
cv2.destroyAllWindows()